### ISSUE TITLE
[Bug Report]: Unable to delete any backups

### ISSUE THREAD

**Issue by zLevii** [WitherHosting/Bug-Tracker#1]
### Expected Behaviour

The backup I want to delete should be deleted

### Final Outcome

An error occurs 

### Steps to Reproduce Issue

```text
Go to backups tab and try to delete any backup
```

### Screenshots

![image](https://github.com/WitherHosting/Bug-Tracker/assets/44142585/e481b34d-2ceb-4194-a0c8-01b3fd6b877d)

### Web Origin

Web: WP-01 Version: 3.0.1

**Comment by RediPanda** [comment]
Hi there! Thanks for letting us know with the issue and I believe we've patched this during our last hotfix. Could you let me know whether the issue is resolved?

**Comment by zLevii** [comment]
Seems to be fixed, thanks
