### ISSUE TITLE
[Bug Report]: Multiserver UI improvements

### ISSUE THREAD

**Issue by vijaypondini** [WitherHosting/Bug-Tracker#11]
### Expected Behaviour

The page should redirect back to server list after creating a multiserver, the page should reload after deleting a multiserver

### Final Outcome

It didn't

### Steps to Reproduce Issue

```text
Pretty straightforward
```

**Comment by RediPanda** [comment]
Resolved in [9f2d299](https://github.com/WitherHosting/WitherPanel-v3/commit/9f2d2998e2acc94d59adb8c15e78b7f0bb6bd054)
