### ISSUE TITLE
[Bug Report]: Forgot password page not in line with styling of the other pages

### ISSUE THREAD

**Issue by vijaypondini** [WitherHosting/Bug-Tracker#12]
### Expected Behaviour

The forgot password page is not in line with styling of the 2fa/login page. Additinoally, when you hover over "return to login" button, it makes the text black, making it disappear

### Final Outcome

Isn't stylized

### Steps to Reproduce Issue

```text
n/a
```

### Screenshots

![image](https://github.com/WitherHosting/Bug-Tracker/assets/70318494/85fde91a-a019-4607-8915-5ab3f1ebec87)

**Comment by vijaypondini** [comment]
The same behaviour of hover text becomes black exists on 2fa's "I've lost my device" nad "return to login"

**Comment by RediPanda** [comment]
Resolved in [4fab561](https://github.com/WitherHosting/WitherPanel-v3/commit/4fab561e5623106c7828c6faa5dff3ce0fa8c1c0)
