### ISSUE TITLE
[Bug Report]: Console spacing broke again

### ISSUE THREAD

**Issue by zLevii** [WitherHosting/Bug-Tracker#13]
### Expected Behaviour

Console spacing should be minimal

### Final Outcome

Console spacing has 2 empty line spaces

### Steps to Reproduce Issue

The steps are in #5 `(https://github.com/WitherHosting/Bug-Tracker/issues/5)`

### Screenshots

![image](https://github.com/WitherHosting/Bug-Tracker/assets/44142585/7cc08f3c-57c0-4ff3-9df2-7f6eec37d1b4)

### Web Origin

Web: WP-01 Version: 3.0.3

**Comment by RediPanda** [comment]
Merge and track with #14
