### ISSUE TITLE
The old panel used to show how many players online in the server :)

### ISSUE THREAD

**Issue by HonestWord** [WitherHosting/Bug-Tracker#15]
Hello :D

The old panel used to show how many players online in the server can we have that again in the new panel :) ! 

+ when the panels resize sometimes the part that says "console/ files...etc" won't show up or will convert the console not like the old perfect panel !  :D 

Thanks  :)

**Comment by RediPanda** [comment]
Added this feature back in 3.0.6 [3006296088c33ae154d93832d16e0e9cbdd98776], will be pushed to live soon! :)
