### ISSUE TITLE
[Bug Report]: Deleting files

### ISSUE THREAD

**Issue by Amzy7** [WitherHosting/Bug-Tracker#16]
### Expected Behaviour

The dashboard is meant to delete the file I selected

### Final Outcome

When I select the file and press delete it states that "An error occurred on the remote host: Cannot move or rename file, destination already exists.. (request id: d59283c7-d74c-449e-87e7-4ac50d9cdad6)". It states that I cannot "move or rename files" however Im attempting to delete it. This is quite annoying as before the update this didnt really happen.

### Steps to Reproduce Issue

```text
1) Select the file(s) you want to delete
2) Press the delete button
```

### Screenshots

![Screenshot 2023-08-08 220058](https://github.com/WitherHosting/Bug-Tracker/assets/74989357/7b81c8bc-afa0-48b5-b5a0-ec001d35e611)

### Web Origin

Web: WP-US-EAST-01 | Version: 3.0.5

**Comment by vijaypondini** [comment]
Should be fixed in v3.0.6H1
