### ISSUE TITLE
[Bug Report]: Live chat missing from Wither panel

### ISSUE THREAD

**Issue by zLevii** [WitherHosting/Bug-Tracker#2]
### Expected Behaviour

Expect to see a live chat icon at the bottom of the screen

### Final Outcome

No live chat icon

### Steps to Reproduce Issue

```text
Open https://witherpanel.com/ and look for a live chat icon
```

### Screenshots

![image](https://github.com/WitherHosting/Bug-Tracker/assets/44142585/30ea5701-359e-4c82-88a9-85c6ca543c1a)

### Web Origin

Web: WP-01 Version: 3.0.1

**Comment by RediPanda** [comment]
Issued resolved in [c814239](https://github.com/WitherHosting/WitherPanel-v3/commit/c8142399d774df84063b731317d3907971d11335), will be effective in the next hotfix!
