### ISSUE TITLE
[Bug Report]: The IP and node text overlap on mobile

### ISSUE THREAD

**Issue by MrRazamataz** [WitherHosting/Bug-Tracker#4]
### Expected Behaviour

Not to overlap the text of the server IP/port and the node

### Final Outcome

The IP:port and node overlap on mobile

### Steps to Reproduce Issue

```text
Go to witherpanel.com on a mobile device.
```

### Screenshots

![image](https://github.com/WitherHosting/Bug-Tracker/assets/56600481/e0da2b72-8c55-47a0-978e-d30e8dd964bd)

### Web Origin

WP-01

**Comment by RediPanda** [comment]
Should be patched in [0055bad](https://github.com/WitherHosting/WitherPanel-v3/commit/0055bad6a613d6558129ca9af4e2d52c2eb0e0da). Waiting for other patches before we can roll a hotfix to live.
