### ISSUE TITLE
[Bug Report]: Unable to create Discord bot server

### ISSUE THREAD

**Issue by zLevii** [WitherHosting/Bug-Tracker#6]
### Expected Behaviour

You should be able to create a discord bot server

### Final Outcome

An error occurs

### Steps to Reproduce Issue

```text
Try to create a discord bot server.
```

### Screenshots

![image](https://github.com/WitherHosting/Bug-Tracker/assets/44142585/3d184c91-3cf2-4766-a125-76b9bb97b468)

### Web Origin

Web: WP-01 Version: 3.0.1

**Comment by RediPanda** [comment]
Issue should be resolved now! Thanks for reporting this!
