### ISSUE TITLE
[Bug Report]: BungeeCord Server won't start due to not finding "server.jar"

### ISSUE THREAD

**Issue by WakBack** [WitherHosting/Bug-Tracker#7]
### Expected Behaviour

The server should start under bungeecord.jar

### Final Outcome

Server didn't start under server.jar error

### Steps to Reproduce Issue

```text
1. Start or Restart the server.
2. Get error: couldn't find the server.jar. (Bungeecord uses bungeecord.jar)
3. Server fails to start or restart.

Note: To get around this I changed bungeecord.jar to server.jar. Renaming the file appeared to allow the server to start but still doesn't work and players still can't access the server through bungee. When players try and join it shows the message: "You are not whitelisted" despite no whitelist being enabled.
```

**Comment by Kaludii** [comment]
Did you change the startup command to match your .jar file? It might have gotten defaulted to the original startup command.

**Comment by WakBack** [comment]
I didn't change it. I changed the name of bungee cord.jar to server.jar in
file manager.

**Comment by RediPanda** [comment]
Hi @WakBack, did you install Bungeecord by creating a Multiserver or by changing the server software from the `Server Version` tab?

**Comment by WakBack** [comment]
This is no longer an issue, my issue now is that I no longer have access to
my sub domain after the website change happened so Im not sure what
happened.

**Comment by RediPanda** [comment]
No worries. Are you taking about existing subdomains before the migration or can you not see the subdomain page/subdomain list?

**Comment by WakBack** [comment]
When the change was made the sub domain was lost and now I can't access it
on the website either.

**Comment by RediPanda** [comment]
Hi @WakBack , we've managed to identify the problem on our hand and stitched a few things to resolve the rendering issues with the subdomains. Could we get you to check to see whether your sub-domains are back?

**Comment by RediPanda** [comment]
Could you provide us your Server ID so we can take a thorough looking into this?

**Comment by WakBack** [comment]
I am able to get the subdomain again. However, I am unable to use it to log
into the server. Where would the server ID be?

**Comment by RediPanda** [comment]
The server ID can be located both in the URL or the random hash string next to the hashtag in your server stats box.

Alternatively, you can give deleting your subdomain and re-creating it a try to push a DNS zone update on our end and see whether you're able to connect to the server via that subdomain.
