### ISSUE TITLE
Please bring back the old panel it was better  :)

### ISSUE THREAD

**Issue by HonestWord** [WitherHosting/Bug-Tracker#8]
### Expected Behaviour

Please bring back the old panel it was better  :)

### Final Outcome

Please bring back the old panel it was better  :)

### Steps to Reproduce Issue

```text
Make it optional to pick between panels please + there's no support chat in the new panels :)
```

**Comment by MrRazamataz** [comment]
Whats wrong with the new panel? Please leave suggestions and we can take a look into incorporating them, however, we will not be bringing back the old panel.

**Comment by RediPanda** [comment]
Hi @HonestWord , we're sorry to hear that you are not satisfied with the end product of the panel. Unfortunately the panel upgrade was necessary to support some new features, a lot of bug-fixes from v2, along with paving in systems to support newer features in the future as we plan to improve the panel along our journey.

We do however appreciate any form of feedback and constructive criticism; so if you believe there are pain-points to be identified on our software please don't hesitate to let us know so we can improve everyone's experience with our game panel.

In regards to the Live Chat bubble being missing, it has returned in (3.0.2).
