### ISSUE TITLE
[Dashboard error]: (It will not let me install any version of forge)

### ISSUE THREAD

**Issue by Piratoide** [WitherHosting/Bug-Tracker#9]
### Expected Behaviour

I was hoping to buy my server and be able to install everything to play but I see that it is not possible

### Final Outcome

IT WON'T LET ME INSTALL FORGE ON THE SERVER :c

### Steps to Reproduce Issue

```text
It stays loading infinitely, does not install anything. I really wanted to play today.
```

### Screenshots

https://media.discordapp.net/attachments/856013422072430593/1133907094232367185/image.png?width=1394&height=659

### Web Origin

https://witherpanel.com/server/d51a0d24/versions

**Comment by RediPanda** [comment]
Hi there! We're terribly sorry to hear that you encountered issues during the install operation. As of 3.0.2 this issue should be fixed. Please re-open the issue if you encounter any issues!
